find existed friend request and delete them based on provided email id
KoushikMallik-developer/split-it-api-v2 pull request #27
Opened 2024-12-28 20:50 UTC by animeshrick

### Overview

> Github Issue:[ #26 ](https://github.com/KoushikMallik-developer/split-it-api-v2/issues/26)

**What was the problem:**
Remove user friend request

**How was this solved:**
find existed friend request and delete them based on provided email id

**Features:**
- new endpoint for remove friend request

**Services to be impacted:**
- `split-it-api-v2`

**Example Code or Screenshot:**
```
Example Code or Screenshot
```

**_For the PR Creator_**

- [ ] Filled out entirely of PR Template.
- [ ] Changes meet acceptance criteria defined in ticket.
- [ ] Unit Tests Passed. :tada:
- [ ] Tested on DEV Env.
- [ ] Tested on QA Env.

2024-12-29 09:07 UTC, KoushikMallik-developer requested changes

2024-12-29 09:07 UTC, KoushikMallik-developer commented on friends/serializers/remove_friend_request_serializer.py
> +            )
Why are you fetching the friend request list?

2024-12-29 09:07 UTC, KoushikMallik-developer commented on friends/serializers/remove_friend_request_serializer.py
> +        ).exists()
Fetch it directly from db, no need to fetch the list first.

2024-12-29 09:07 UTC, KoushikMallik-developer commented on friends/friend_exceptions/friend_exceptions.py
> +        logging.error(self.msg)
No need.

2024-12-29 09:07 UTC, KoushikMallik-developer commented on friends/friend_exceptions/friend_exceptions.py
> +class FriendRequestExistenceError(AUTHBaseException):
Update the name to `FriendRequsetNotFoundError`

2024-12-29 09:07 UTC, KoushikMallik-developer commented on friends/friend_exceptions/friend_exceptions.py
> +            self.msg = "The provided email is not part of the friend request list."
Update the message to `You have not sent friend request to this user.`

2025-01-01 16:03 UTC, KoushikMallik-developer requested changes

2025-01-01 16:03 UTC, KoushikMallik-developer commented on friends/serializers/remove_friend_request_serializer.py
> +            raise FriendRequestNotFoundError()
change the variable name to `existing_friend_request`

2025-01-01 16:03 UTC, KoushikMallik-developer commented on friends/serializers/remove_friend_request_serializer.py
> +            raise ValueError("user_email is required.")
Change the message to `Email is required`

2025-01-01 16:03 UTC, KoushikMallik-developer commented on friends/views/remove_friend_request.py
> +                    "successMessage": None,
use exception handler class

2025-01-01 16:07 UTC, animeshrick commented on friends/views/remove_friend_request.py
> +                    "successMessage": None,
we'll do it later

2025-01-01 16:14 UTC, KoushikMallik-developer approved these changes

2025-01-01 16:15 UTC, merged