24 handle exceptions
KoushikMallik-developer/split-it-api-v2 pull request #30
Opened 2024-12-29 14:08 UTC by KoushikMallik-developer

### Overview

> resolved Github Issue:[ #24 ](https://github.com/KoushikMallik-developer/split-it-api-v2/issues/[24])

**What was the problem:**
We needed to handle all the exception in proper manner and also unit tests.

**How was this solved:**
We have added exception handler and unit tests.

**Features:**
- Exception Handler
- Unit Tests

**Services to be impacted:**
- `split-it-api-v2`

**Example Code or Screenshot:**
```
Example Code or Screenshot
```
![image](https://github.com/user-attachments/assets/e52049e5-f9f0-4916-ac5f-8f14aae7d469)

**_For the PR Creator_**

- [ ] Filled out entirely of PR Template.
- [ ] Changes meet acceptance criteria defined in ticket.
- [ ] Unit Tests Passed. :tada:
- [ ] Tested on DEV Env.
- [ ] Tested on QA Env.

2024-12-31 17:48 UTC, animeshrick requested changes

2024-12-31 17:48 UTC, animeshrick commented on auth_api/tests/handlers/test_exception_handlers.py
> +class TestExceptionHandler:
why we need this ?

2025-01-01 07:49 UTC, KoushikMallik-developer commented on auth_api/tests/handlers/test_exception_handlers.py
> +class TestExceptionHandler:
This is the unit test class for ExceptionHandler feature what I have added in this feature ticket.

2025-01-01 15:40 UTC, animeshrick approved these changes

2025-01-01 15:43 UTC, merged